sudo: false

notifications:
  email: false

language: node_js

node_js:
  - node

install:
  - yarn install
  - yarn audit

script:
  - yarn lint
  - yarn prettier
  - yarn test:coveralls
  - yarn build
